sudo: false

notifications:
  email: false

os: osx

matrix:
  include:
    - language: swift
      name: "Cocoapods BlueprintUI (Xcode 11.2)"
      xcode_scheme: BlueprintUI-Unit-Tests
      osx_image: xcode11.2
      xcode_workspace: SampleApp.xcworkspace
      xcode_destination: platform=iOS Simulator,OS=10.3.1,name=iPhone 7 Plus
      before_install:
        - cd SampleApp
        - bundle install
        - bundle exec pod repo update
        - bundle exec pod install

    - language: swift
      name: "SPM (Xcode 11.2)"
      os: osx
      osx_image: xcode11.2
      script:
        - xcodebuild -scheme "BlueprintUI-Package" test -destination "name=iPad Pro (9.7-inch)"

